name: Build and delivery a Gradle project
on:
  workflow_call:
    inputs:
      build-command:
        description: 'The command executed in the build phase'
        default: './gradlew assemble --parallel'
        required: false
        type: string
      check-command:
        description: 'The command executed in the check phase'
        default: './gradlew check --parallel'
        required: false
        type: string
      codecov-os:
        description: 'The operating systems running codecov. Multiple OSs can be listed (the string is searched for the current os as substring)'
        default: 'Linux'
        required: false
        type: string
      deploy-branches:
        description: 'The branches from where the deployment always happens. Multiple branches can be listed (the string is searched for the current os as substring)'
        default: develop
        required: false
        type: string
      deploy-command:
        description: 'The condition triggering a deploy run'
        default: "./gradlew publishKotlinMavenPublicationToMavenCentralRepository"
        required: false
        type: string
      deploy-default-branch:
        description: 'True if deployment should always run for the default branch'
        default: true
        required: false
        type: boolean
      deploy-os:
        description: 'The operating systems from where the deployment happens. Multiple OSs can be listed (the string is searched for the current os as substring)'
        default: 'Linux'
        required: false
        type: string
      deploy-repo:
        description: 'The repository from which the deployments can happen. Partial names supported'
        default: 'DanySK/'
        required: false
        type: string
      deploy-tags:
        description: 'Whether tags should always be deployed'
        default: true
        required: false
        type: boolean
      maven-central-username:
        description: 'Username for Maven Central'
        default: 'danysk'
        required: false
        type: string
    secrets:
      github-token:
        required: false
      gradle-publish-secret:
        required: false
      gradle-publish-key:
        required: false
      maven-central-password:
        required: false
      signing-key:
        required: false
      signing-password:
        required: false

jobs:
  Build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    env:
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: danysk/action-checkout@0.1.0
      - name: Get branch name
        id: branch
        uses: tj-actions/branch-names@v5
      - name: Configure the Windows Pagefile
        if: ${{ runner.os == 'Windows' }}
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/jdks
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        run: |
          ${{ inputs.build-command }}
      - name: Check
        shell: bash
        run: |
          ${{ inputs.check-command }}
      - name: CodeCov
        if: contains(inputs.codecov-os, runner.os)
        uses: codecov/codecov-action@v2
      - name: Deploy
        if: >-
          contains(inputs.deploy-os, runner.os)
          && contains(github.repository, input.deploy-repo)
          && (
            contains(inputs.deploy-branches, steps.branch.outputs.current_branch)
            || inputs.deploy-default-branch && steps.branch.outputs.is_default
            || inputs.deploy-tags && steps.branch.outputs.is_tag
          )
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.gradle-publish-secret }}
          GRADLE_PUBLISH_KEY: ${{ secrets.gradle-publish-key }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.maven-central-password }}
          MAVEN_CENTRAL_USERNAME: ${{ inputs.maven-central-username }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.signing-key }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.signing-password }}
          SIGNING_PASSWORD: ${{ secrets.signing-password }}
        run: |
          ${{ inputs.deploy-command }}
      - name: Turn off the Gradle Daemon
        shell: bash
        run: ./gradlew --stop
      - name: Cleanup the Gradle cache
        if: ${{ runner.os != 'Windows' }}
        shell: bash
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Force the Gradle cleanup on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          Remove-Item -Force c:\Users\runneradmin\.gradle\caches\modules-2\modules-2.lock
          Remove-Item -Force c:\Users\runneradmin\.gradle\caches\modules-2\gc.properties
