name: Bump version number and create a release
on:
  workflow_call:
    inputs:
      update-version:
        description: 'Whether the commit distance from the last tag should update the major, minor, patch, or pre-release version once new commits are detected'
        default: 'patch'
        required: false
        type: string
      pre-release-tag:
        description: 'An optional pre-release symbol, used only if update-version is pre-release'
        default: 'dev'
        required: false
        type: string
      target-branch:
        description: 'New releases will be created only if there are new commits on the indicated branch'
        default: 'master'
        required: false
        type: string
      artifacts:
        description: 'An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs). E.g., "release.tar.gz,foo/*.txt"'
        default: ''
        required: false
        type: string
    
jobs:
  Create-Release:
    runs-on: ubuntu-latest
    if: endsWith(github.ref, inputs.target-branch)
    steps:
      - name: Compute the scripts version
        id: script-version
        run: |
          # Idea: the regex matcher of Renovate keeps this string up to date automatically
          # The version is extracted and used to access the correct version of the scripts
          USES=$(cat <<TRICK_RENOVATE
          - uses: danysk/workflows@0.1.0-dev27
          TRICK_RENOVATE
          )
          echo "Scripts update line: \"$USES\""
          echo "Computed version: \"${USES#*@}\""
          echo "::set-output name=script-version::${USES#*@}"
      - name: Checkout
        uses: danysk/action-checkout@0.2.1
      - name: Compute version
        id: compute-version
        run: |
          curl -o deduce_version 'https://raw.githubusercontent.com/DanySK/workflows/${{ steps.script-version.outputs.script-version }}/deduce_version.rb'
          ruby deduce_version ${{ inputs.update-version }} ${{ inputs.pre-release-tag }}
      - name: Create release with changelog
        uses: danysk/create-release-action@0.1.19
        with:
          artifacts: ${{ inputs.artifacts }}
          version: ${{ steps.compute-version.outputs.version }}
          token: ${{ github.token }}
