on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: danysk/action-checkout@0.1.0
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        token: ${{ secrets.GITHUB_TOKEN }}
