name: Create release on tag
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Build Changelog
      uses: danysk/compute-changelog-action@0.1.64
      with:
        push-changes: false
        token: ${{ github.token }}
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG.md"
        token: ${{ github.token }}
